export interface Ic38Question {
  id: number;
  chapter: string;
  question: string;
  options: [string, string, string, string];
  correctAnswer: number; // 0..3 index
  explanation: string;
}

export const IC38_QUESTION_BANK: Ic38Question[] = [
  {
    id: 1,
    chapter: 'Chapter 1: Introduction to Insurance',
    question: 'Risk transfer through risk pooling is known as:',
    options: ['Savings', 'Investments', 'Insurance', 'Risk Mitigation'],
    correctAnswer: 2,
    explanation: 'Insurance is defined as the process of risk transfer through pooling contributions from many individuals exposed to similar risks.',
  },
  {
    id: 2,
    chapter: 'Chapter 1: Introduction to Insurance',
    question: 'Which of the following is considered the statutory regulator for the insurance industry in India?',
    options: ['Insurance Authority of India', 'Insurance Regulatory and Development Authority of India (IRDAI)', 'Life Insurance Corporation of India', 'General Insurance Corporation of India'],
    correctAnswer: 1,
    explanation: 'IRDAI (statutory body formed in 2000) regulates and develops the insurance sector in India.',
  },
  {
    id: 3,
    chapter: 'Chapter 1: Introduction to Insurance',
    question: 'The origin of modern commercial insurance business is traced back to:',
    options: ['Bottomry Club', 'Lloyds Coffee House in London', 'Rhodes Maritime Guild', 'Malhotra Committee'],
    correctAnswer: 1,
    explanation: 'Modern commercial insurance originated at Lloyds Coffee House in London where ship merchants met to share marine losses.',
  },
  {
    id: 4,
    chapter: 'Chapter 1: Introduction to Insurance',
    question: 'Setting aside financial reserves as a provision for meeting potential future losses is an example of:',
    options: ['Primary burden of risk', 'Secondary burden of risk', 'Risk avoidance', 'Catastrophic risk'],
    correctAnswer: 1,
    explanation: 'Secondary burden of risk consists of the cost of keeping emergency liquid funds and physical/mental strain from anxiety.',
  },
  {
    id: 5,
    chapter: 'Chapter 1: Introduction to Insurance',
    question: 'The first non-life insurer established in India was:',
    options: ['Oriental Life Insurance Co.', 'Triton Insurance Co. Ltd.', 'National Insurance Co. Ltd.', 'Bombay Mutual Assurance Society'],
    correctAnswer: 1,
    explanation: 'Triton Insurance Co. Ltd. was the first non-life insurance company established in India.',
  },
  {
    id: 6,
    chapter: 'Chapter 2: Customer Service',
    question: 'According to the SERVQUAL model, the ability to perform promised services dependably and accurately is called:',
    options: ['Responsiveness', 'Empathy', 'Reliability', 'Tangibles'],
    correctAnswer: 2,
    explanation: 'Reliability is the foundation of trust in customer service.',
  },
  {
    id: 7,
    chapter: 'Chapter 2: Customer Service',
    question: 'Customer Lifetime Value (CLV) is defined as:',
    options: ['Sum of servicing costs incurred over a customer lifetime', 'Sum of economic benefits derived by building a long-term relationship with a customer', 'Rank given to customer based on immediate policy size', 'Maximum insurance coverage granted to a customer'],
    correctAnswer: 1,
    explanation: 'Customer Lifetime Value represents the total economic benefit derived from maintaining a lasting relationship.',
  },
  {
    id: 8,
    chapter: 'Chapter 3: Grievance Redressal',
    question: 'What does IGMS stand for in Indian insurance grievance redressal?',
    options: ['Integrated Grievance Management System', 'Insurance General Management System', 'Indian Grievance Management Scheme', 'Intelligent Grievance Monitoring System'],
    correctAnswer: 0,
    explanation: 'IGMS is IRDAI’s Integrated Grievance Management System acting as a central repository for policyholder complaints.',
  },
  {
    id: 9,
    chapter: 'Chapter 3: Grievance Redressal',
    question: 'Under the Consumer Protection Act, what is the claim compensation limit for the District Forum?',
    options: ['Up to Rs. 20 Lakhs', 'Rs. 20 Lakhs to Rs. 100 Lakhs', 'Above Rs. 100 Lakhs', 'Unlimited'],
    correctAnswer: 0,
    explanation: 'District Forum handles consumer disputes where value of goods/services and compensation claimed is up to Rs. 20 Lakhs.',
  },
  {
    id: 10,
    chapter: 'Chapter 3: Grievance Redressal',
    question: 'What is the maximum monetary award that the Insurance Ombudsman can grant?',
    options: ['Rs. 10 Lakhs', 'Rs. 20 Lakhs', 'Rs. 50 Lakhs', 'Rs. 1 Crore'],
    correctAnswer: 1,
    explanation: 'The Insurance Ombudsman can pass awards up to Rs. 20 Lakhs (including ex-gratia and expenses).',
  },
  {
    id: 11,
    chapter: 'Chapter 4: Regulatory Aspects of Agents',
    question: 'Under IRDAI regulations, an appointment letter issued to an insurance agent must be dispatched within how many days of appointment?',
    options: ['3 days', '7 days', '15 days', '30 days'],
    correctAnswer: 1,
    explanation: 'The letter of appointment must be dispatched not later than 7 days after the appointment of the agent.',
  },
  {
    id: 12,
    chapter: 'Chapter 4: Regulatory Aspects of Agents',
    question: 'A Composite Insurance Agent is allowed to represent at most:',
    options: ['Multiple general insurers', 'One life, one general, one health, and one mono-line insurer', 'Any number of private insurance companies', 'Only public sector companies'],
    correctAnswer: 1,
    explanation: 'A composite agent can act for 1 Life, 1 General, 1 Health, and 1 specialized mono-line insurer.',
  },
  {
    id: 13,
    chapter: 'Chapter 5: Legal Principles of Insurance',
    question: 'Which legal principle requires the insured to disclose all material facts voluntarily and truthfully?',
    options: ['Caveat Emptor', 'Uberrima Fides (Utmost Good Faith)', 'Subrogation', 'Proximate Cause'],
    correctAnswer: 1,
    explanation: 'Uberrima Fides (Utmost Good Faith) mandates complete and accurate disclosure of all material facts.',
  },
  {
    id: 14,
    chapter: 'Chapter 5: Legal Principles of Insurance',
    question: 'Ramesh threatens to harm Mahesh unless Mahesh signs an insurance proposal. This is an example of:',
    options: ['Fraud', 'Undue Influence', 'Coercion', 'Mistake'],
    correctAnswer: 2,
    explanation: 'Coercion involves pressure applied through criminal means or unlawful threats.',
  },
  {
    id: 15,
    chapter: 'Chapter 5: Legal Principles of Insurance',
    question: 'When is insurable interest required to be present in general insurance (e.g., motor/property)?',
    options: ['Only at the time of taking the policy', 'Both at the time of taking the policy and at the time of loss/claim', 'Only at the time of claim settlement', 'Insurable interest is never required'],
    correctAnswer: 1,
    explanation: 'In general insurance, insurable interest must exist both at inception and at the time of loss.',
  },
  {
    id: 16,
    chapter: 'Chapter 5: Legal Principles of Insurance',
    question: 'The principle of Indemnity ensures that:',
    options: ['The insured makes a net profit from the insurance claim', 'The insured is compensated so as to be placed in the same financial position as before the loss', 'The insurer pays twice the sum insured for accidental loss', 'Claims are paid irrespective of actual loss suffered'],
    correctAnswer: 1,
    explanation: 'Indemnity compensates the policyholder for actual loss suffered up to sum insured, preventing profit from loss.',
  },
  {
    id: 17,
    chapter: 'Chapter 5: Legal Principles of Insurance',
    question: 'Subrogation refers to:',
    options: ['Sharing of loss between multiple insurers', 'Transfer of all rights and remedies from the insured to the insurer after paying indemnity', 'Cancellation of policy due to non-payment', 'Adjustment of premium based on claims history'],
    correctAnswer: 1,
    explanation: 'Subrogation transfers the legal rights of recovery against third parties from the insured to the paying insurer.',
  },
  {
    id: 18,
    chapter: 'Chapter 5: Legal Principles of Insurance',
    question: 'In insurance, Proximate Cause is defined as:',
    options: ['The remote cause closest to the time of loss', 'The active, efficient cause that sets in motion a chain of events leading to loss', 'The last event immediately preceding the loss', 'The cause specified by the policyholder'],
    correctAnswer: 1,
    explanation: 'Proximate cause is the dominant and efficient cause setting off a direct unbroken chain of events leading to damage.',
  },
  {
    id: 19,
    chapter: 'Chapter 6: Health Insurance',
    question: 'According to the WHO definition, Health is defined as:',
    options: ['Absence of physical disease only', 'Soundness of body and high earning capacity', 'A state of complete physical, mental, and social well-being and not merely the absence of disease', 'Having high medical insurance cover'],
    correctAnswer: 2,
    explanation: 'WHO defines health as complete physical, mental, and social well-being.',
  },
  {
    id: 20,
    chapter: 'Chapter 6: Health Insurance',
    question: 'Specialist consultative healthcare provided to inpatients on referral (such as oncology or organ transplant) is classified as:',
    options: ['Primary Healthcare', 'Secondary Healthcare', 'Tertiary Healthcare', 'Domiciliary Healthcare'],
    correctAnswer: 2,
    explanation: 'Tertiary healthcare involves advanced specialized consultative medical care and surgeries.',
  },
  {
    id: 21,
    chapter: 'Chapter 7: Insurance Documentation',
    question: 'Under Section 64VB of the Insurance Act 1938:',
    options: ['Premium can be paid after policy expiry', 'No risk can be assumed by the insurer unless premium is received in advance', 'Agents are allowed to retain 50% premium as cash', 'Insurance coverage is granted on credit'],
    correctAnswer: 1,
    explanation: 'Section 64VB dictates advance payment of premium before assumption of risk by an insurer.',
  },
  {
    id: 22,
    chapter: 'Chapter 7: Insurance Documentation',
    question: 'If an insurance agent collects premium from a customer, within how many hours must it be deposited with the insurer?',
    options: ['12 hours', '24 hours (excluding bank/postal holidays)', '48 hours', '7 days'],
    correctAnswer: 1,
    explanation: 'Agents collecting premiums must deposit full funds with the insurer within 24 hours.',
  },
  {
    id: 23,
    chapter: 'Chapter 7: Insurance Documentation',
    question: 'A Prospectus issued by an insurance company must clearly disclose:',
    options: ['Agent commission percentage only', 'Scope of benefits, exclusions, riders, and renewal conditions', 'Internal financial auditing software', 'List of all shareholders'],
    correctAnswer: 1,
    explanation: 'Prospectus contains comprehensive details of coverage, exclusions, riders, and renewal terms for prospective buyers.',
  },
  {
    id: 24,
    chapter: 'Chapter 8: Health Insurance Products',
    question: 'Standard Pre-hospitalization and Post-hospitalization coverage periods in Mediclaim policies are typically:',
    options: ['7 days pre and 15 days post', '30 days pre and 60 days post', '90 days pre and 180 days post', '15 days pre and 30 days post'],
    correctAnswer: 1,
    explanation: 'Standard indemnity health policies cover 30 days pre-hospitalization and 60 days post-hospitalization medical expenses.',
  },
  {
    id: 25,
    chapter: 'Chapter 8: Health Insurance Products',
    question: 'Under IRDAI standardization guidelines, Pre-existing Disease (PED) is defined as any condition diagnosed or treated within how many months prior to policy issuance?',
    options: ['12 months', '24 months', '36 months', '48 months'],
    correctAnswer: 3,
    explanation: 'Pre-existing disease refers to ailments diagnosed or treated within 48 months prior to policy inception.',
  },
  {
    id: 26,
    chapter: 'Chapter 8: Health Insurance Products',
    question: 'In a Family Floater Health Policy:',
    options: ['Each family member has a separate un-shareable sum insured', 'A single sum insured floats and is shared across all covered family members', 'Only the earning parent can claim medical expenses', 'Premium is calculated based on the youngest family member'],
    correctAnswer: 1,
    explanation: 'A family floater offers a single sum insured accessible by any or all covered family members during the policy year.',
  },
  {
    id: 27,
    chapter: 'Chapter 8: Health Insurance Products',
    question: 'Critical Illness insurance policies operate on a:',
    options: ['Indemnity basis (reimbursing exact bills)', 'Fixed benefit basis (paying lump-sum upon diagnosis of covered illness)', 'Co-payment basis only', 'Short-term loan basis'],
    correctAnswer: 1,
    explanation: 'Critical illness policies pay a fixed lump-sum sum insured upon diagnosis of specified critical ailments like cancer or stroke.',
  },
  {
    id: 28,
    chapter: 'Chapter 8: Health Insurance Products',
    question: 'What is the Free-Look Period allowed to policyholders for reviewing a new individual health policy?',
    options: ['7 days', '15 days', '30 days', '45 days'],
    correctAnswer: 1,
    explanation: 'IRDAI mandates a 15-day free-look period from date of policy receipt to cancel and claim refund if unsatisfied.',
  },
  {
    id: 29,
    chapter: 'Chapter 9: Underwriting',
    question: 'In health insurance underwriting, the primary risk evaluation concept is:',
    options: ['Mortality', 'Morbidity (likelihood of falling ill or requiring hospitalization)', 'Inflation rate', 'Property valuation'],
    correctAnswer: 1,
    explanation: 'Morbidity measures the frequency and severity of sickness/hospitalization for underwriting health policies.',
  },
  {
    id: 30,
    chapter: 'Chapter 9: Underwriting',
    question: 'Primary or Field Level Underwriting is conducted by:',
    options: ['Head Office Chief Actuary', 'The Insurance Agent / Sales Advisor', 'Third Party Administrator (TPA)', 'IRDAI Auditor'],
    correctAnswer: 1,
    explanation: 'The agent acts as the primary field underwriter by interacting directly with the proposer and observing hazards.',
  },
  {
    id: 31,
    chapter: 'Chapter 9: Underwriting',
    question: 'Dishonesty or deliberate concealment of health facts by a proposer to fraudulently claim benefits is known as:',
    options: ['Physical hazard', 'Moral hazard', 'Legal hazard', 'Catastrophic hazard'],
    correctAnswer: 1,
    explanation: 'Moral hazard refers to character defects, dishonesty, or deliberate misrepresentation by the insured.',
  },
  {
    id: 32,
    chapter: 'Chapter 10: Health Claims',
    question: 'What does TPA stand for in health insurance claim management?',
    options: ['Total Protection Agency', 'Third Party Administrator', 'Technical Processing Authority', 'Timely Payment Association'],
    correctAnswer: 1,
    explanation: 'Third Party Administrators (TPAs) are IRDAI licensed entities handling cashless network administration and claims processing.',
  },
  {
    id: 33,
    chapter: 'Chapter 10: Health Claims',
    question: 'International Classification of Diseases (ICD) codes are used in claims processing for:',
    options: ['Calculating agent commissions', 'Standardized coding of medical diagnoses and diseases', 'Determining vehicle depreciation', 'Filing police FIRs'],
    correctAnswer: 1,
    explanation: 'WHO ICD codes provide a global standardized coding system for medical diagnoses.',
  },
  {
    id: 34,
    chapter: 'Chapter 10: Health Claims',
    question: 'For an emergency hospital admission, within how many hours should claim intimation typically be sent to the insurer/TPA?',
    options: ['24 hours', '48 hours', '7 days', '15 days'],
    correctAnswer: 0,
    explanation: 'Emergency hospital admissions require intimation within 24 hours of admission.',
  },
  {
    id: 35,
    chapter: 'Chapter 11: Principles of Insurance',
    question: 'Risk pooling is based on the mathematical principle known as:',
    options: ['Law of Supply and Demand', 'Law of Large Numbers', 'Theory of Relativity', 'Principle of Compound Interest'],
    correctAnswer: 1,
    explanation: 'The Law of Large Numbers states that larger pool sizes make actual average losses closer to expected losses.',
  },
  {
    id: 36,
    chapter: 'Chapter 11: Principles of Insurance',
    question: 'Which of the following is a Pure Risk (insurable)?',
    options: ['Investing in stock market shares', 'Gambling on horse racing', 'Damage to a factory caused by accidental fire', 'Speculating in currency exchange rates'],
    correctAnswer: 2,
    explanation: 'Pure risk involves situations resulting only in loss or no loss (never financial gain), which is insurable.',
  },
  {
    id: 37,
    chapter: 'Chapter 12: Documentation',
    question: 'A provisional document issued by an insurer to confirm temporary protection while a regular policy document is being prepared is called a:',
    options: ['Cover Note', 'Endorsement', 'Prospectus', 'Renewal Notice'],
    correctAnswer: 0,
    explanation: 'A Cover Note provides interim evidence of insurance cover until the final policy bond is issued.',
  },
  {
    id: 38,
    chapter: 'Chapter 12: Documentation',
    question: 'If policy terms need to be modified or updated after issuance, the document setting out the amendment is called an:',
    options: ['Endorsement', 'Warranty', 'Actuarial Certificate', 'Underwriting Slip'],
    correctAnswer: 0,
    explanation: 'Endorsements are attached to policy documents to record variations, additions, or amendments in terms.',
  },
  {
    id: 39,
    chapter: 'Chapter 13: Premium Rating',
    question: 'Pure Premium is calculated to cover:',
    options: ['Expected loss payments only', 'Administrative expenses and office rent', 'Agent commissions and profits', 'Taxes and marketing costs'],
    correctAnswer: 0,
    explanation: 'Pure premium is the portion of premium calculated solely to pay expected claim losses without loading for expenses.',
  },
  {
    id: 40,
    chapter: 'Chapter 14: Personal & Retail Insurance',
    question: 'In Motor Insurance, IDV stands for:',
    options: ['Insured’s Declared Value', 'Initial Depreciation Value', 'Individual Driver Value', 'International Damage Value'],
    correctAnswer: 0,
    explanation: 'IDV (Insured’s Declared Value) is the maximum sum insured payable in case of total loss or theft of a vehicle.',
  },
  {
    id: 41,
    chapter: 'Chapter 14: Personal & Retail Insurance',
    question: 'Under the Motor Vehicles Act 1988, which type of motor insurance coverage is mandatory for all vehicles plying on public roads?',
    options: ['Own Damage Cover', 'Third Party Liability Insurance', 'Zero Depreciation Cover', 'Personal Accident Cover for Passengers'],
    correctAnswer: 1,
    explanation: 'Third Party Liability insurance is statutory and compulsory under Indian law.',
  },
  {
    id: 42,
    chapter: 'Chapter 15: Commercial Insurance',
    question: 'Business Interruption (Consequential Loss) insurance covers loss of:',
    options: ['Raw materials damaged by rain', 'Gross profit and standing charges resulting from business stoppage due to an insured peril', 'Physical machinery wear and tear', 'Stolen cash from till'],
    correctAnswer: 1,
    explanation: 'Business Interruption insurance covers lost gross profits and ongoing fixed costs during factory downtime.',
  },
  {
    id: 43,
    chapter: 'Chapter 15: Commercial Insurance',
    question: 'Which commercial policy indemnifies employers against financial loss caused by white-collar crimes or employee dishonesty/embezzlement?',
    options: ['Contractors All Risk Policy', 'Fidelity Guarantee Insurance', 'Public Liability Policy', 'Workmen Compensation Policy'],
    correctAnswer: 1,
    explanation: 'Fidelity Guarantee insurance covers employer loss resulting from fraud, forgery, or theft by employees.',
  },
  {
    id: 44,
    chapter: 'Chapter 15: Commercial Insurance',
    question: 'Under the Public Liability Insurance Act 1991, compensation for actual medical expenses due to a hazardous substance accident is capped at:',
    options: ['Rs. 6,250', 'Rs. 12,500', 'Rs. 25,000', 'Rs. 50,000'],
    correctAnswer: 1,
    explanation: 'Actual medical expenses under PLI Act 1991 are compensated up to a maximum limit of Rs. 12,500.',
  },
  {
    id: 45,
    chapter: 'Chapter 16: Claims Procedure',
    question: 'Under Section 64UM of the Insurance Act, an independent licensed surveyor is required for general insurance claims exceeding what value?',
    options: ['Rs. 5,000', 'Rs. 20,000', 'Rs. 50,000', 'Rs. 1 Lakh'],
    correctAnswer: 1,
    explanation: 'Section 64UM mandates employing an approved surveyor for loss assessment on claims equal to or exceeding Rs. 20,000.',
  },
  {
    id: 46,
    chapter: 'Chapter 16: Claims Procedure',
    question: 'What does TAT stand for in insurance claim processing?',
    options: ['Total Assessment Time', 'Turnaround Time', 'Time and Transfer', 'Technical Audit Term'],
    correctAnswer: 1,
    explanation: 'Turnaround Time (TAT) measures the speed and efficiency of processing intimation to claim settlement.',
  },
  {
    id: 47,
    chapter: 'Chapter 16: Claims Procedure',
    question: 'Upon full payment of a total loss claim, damaged residual property taken over by the insurer is known as:',
    options: ['Salvage', 'Endorsement', 'Deductible', 'Re-insurance'],
    correctAnswer: 0,
    explanation: 'Salvage refers to damaged asset remnants transferred to the insurer upon paying full claim value.',
  },
  {
    id: 48,
    chapter: 'Chapter 16: Claims Procedure',
    question: 'A formal legal method of resolving insurance claim quantum disputes out of court by appointing an independent referee is:',
    options: ['Arbitration', 'Litigation', 'Repudiation', 'Co-payment'],
    correctAnswer: 0,
    explanation: 'Arbitration under the Arbitration Act allows private, out-of-court resolution of quantum disputes.',
  },
  {
    id: 49,
    chapter: 'Chapter 14: Personal Accident',
    question: 'In Personal Accident insurance, Permanent Total Disability (PTD) benefit pays:',
    options: ['10% of sum insured per year', '100% of sum insured', 'Weekly allowance up to 10 weeks only', 'Only medical bill reimbursement'],
    correctAnswer: 1,
    explanation: 'PTD benefit pays 100% of capital sum insured in the event of permanent total disablement (e.g., loss of both limbs or eyes).',
  },
  {
    id: 50,
    chapter: 'Chapter 8: Micro Insurance',
    question: 'Micro-insurance regulations restrict individual sum insured to below:',
    options: ['Rs. 30,000', 'Rs. 1 Lakh', 'Rs. 2 Lakhs', 'Rs. 5 Lakhs'],
    correctAnswer: 0,
    explanation: 'IRDA Micro-Insurance Regulations cap sum insured under micro-insurance schemes at Rs. 30,000.',
  },
];
